tap argon/mas
brew mas

tap caskroom/cask

## editor
cask 'android-studio'
cask 'iterm2'
cask 'evernote'
cask 'skitch'

## browser
cask 'google-chrome'
brew tap caskroom/versions
cask 'google-chrome-canary'

## programming tool
cask 'arduino'
cask 'cyberduck'
cask 'docker'
cask 'imageoptim'
cask 'java'
cask 'dbeaver-community' # not work, please install by pkg

## display
cask 'insomniax'
cask 'hyperswitch'
cask 'shiftit'

## communication
cask 'slack'
cask 'skype'

## useful
cask 'clipy'
cask 'cmd-eikana' # keyremap4macbook
cask 'dropbox'
cask 'the-unarchiver'
cask 'vlc'
tap homebrew/cask-drivers
cask 'logitech-options'

## docker is better
# cask 'virtualbox'
# cask 'vagrant'
# cask 'vagrant-manager'

tap homebrew/core
tap neovim/neovim
# brew neovim/neovim/neovim
brew fpp
brew gcc@5
brew git
brew gmp
brew heroku
brew isl@0.14
brew jq
brew libmpc
brew mpfr
brew wget
brew nodejs
brew yarn
brew pyenv
brew maven
brew tree
brew certbot
brew openssl
brew ffmpeg
brew go

tap homebrew/versions

tap rcmdnk/file
brew brew-file

appstore 408981434 iMovie (10.1.4)
appstore 539883307 LINE (5.1.1)
appstore 497799835 Xcode (8.2.1)
